SELECT * WHERE 
{ 
    ?subject <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <schema://oulipo/${type}>;   
    <#list queryParams?keys as key> 
    	<#if queryParams[key]?starts_with("ted://")>
   		 <schema://oulipo/${key}> <${queryParams[key]}>;
   		<#else>
   		 <schema://oulipo/${key}> "${queryParams[key]}";
   		</#if>
	</#list> 
    ?predicate ?object .   
    FILTER regex(str(?subject), "ted://${networkId}") .
}